### ISSUE TITLE
panda unsuccessful run

### ISSUE THREAD

**Issue by ShakeWeLy** [microsoft/visual-chatgpt#127]
Traceback (most recent call last):
  File "D:\Pydata\anacondai\envs\visgpt\lib\site-packages\altair\utils\core.py", line 20, in <module>
    from pandas.api.types import infer_dtype as _infer_dtype
ModuleNotFoundError: No module named 'pandas.api'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\AI\visual-chatgpt-main\visual_chatgpt.py", line 5, in <module>
    import gradio as gr
  File "D:\Pydata\anacondai\envs\visgpt\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "D:\Pydata\anacondai\envs\visgpt\lib\site-packages\gradio\components.py", line 21, in <module>
    import altair as alt
  File "D:\Pydata\anacondai\envs\visgpt\lib\site-packages\altair\__init__.py", line 4, in <module>
    from .vegalite import *
  File "D:\Pydata\anacondai\envs\visgpt\lib\site-packages\altair\vegalite\__init__.py", line 2, in <module>
    from .v4 import *
  File "D:\Pydata\anacondai\envs\visgpt\lib\site-packages\altair\vegalite\v4\__init__.py", line 2, in <module>
    from .schema import *
  File "D:\Pydata\anacondai\envs\visgpt\lib\site-packages\altair\vegalite\v4\schema\__init__.py", line 2, in <module>
    from .core import *
  File "D:\Pydata\anacondai\envs\visgpt\lib\site-packages\altair\vegalite\v4\schema\core.py", line 4, in <module>
    from altair.utils.schemapi import SchemaBase, Undefined, _subclasses
  File "D:\Pydata\anacondai\envs\visgpt\lib\site-packages\altair\utils\__init__.py", line 1, in <module>
    from .core import (
  File "D:\Pydata\anacondai\envs\visgpt\lib\site-packages\altair\utils\core.py", line 23, in <module>
    from pandas.lib import infer_dtype as _infer_dtype
ModuleNotFoundError: No module named 'pandas.lib'

how to solove? panda vison?

**Comment by ShakeWeLy** [comment]
Because of a misoperation, I installed the panda in advance and then ran the file: requirement, but now running the panda reports an error

**Comment by ShakeWeLy** [comment]
help！！！
