### ISSUE TITLE
Unable to modify any photo

### ISSUE THREAD

**Issue by congling** [microsoft/visual-chatgpt#130]
input: (the picture is generated) 
![b25195b2](https://user-images.githubusercontent.com/778371/224563316-fd6f8ea2-d54c-41c9-996c-f335143b6332.png)

prompt: replace the girl with a boy

report error:

Entering new AgentExecutor chain...
 Yes
Action: Replace Something From The Photo
Action Input: image/b25195b2.png, girl, boyreplace_part_of_image: replace_with_txt  boy
Traceback (most recent call last):
  File "/root/miniconda3/envs/visgpt/lib/python3.8/site-packages/gradio/routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/envs/visgpt/lib/python3.8/site-packages/gradio/blocks.py", line 1032, in process_api
    result = await self.call_function(
  File "/root/miniconda3/envs/visgpt/lib/python3.8/site-packages/gradio/blocks.py", line 844, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/miniconda3/envs/visgpt/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/miniconda3/envs/visgpt/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/visgpt/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "visual_chatgpt.py", line 908, in run_text
    res = self.agent({"input": text})
  File "/root/miniconda3/envs/visgpt/lib/python3.8/site-packages/langchain/chains/base.py", line 168, in __call__
    raise e
  File "/root/miniconda3/envs/visgpt/lib/python3.8/site-packages/langchain/chains/base.py", line 165, in __call__
    outputs = self._call(inputs)
  File "/root/miniconda3/envs/visgpt/lib/python3.8/site-packages/langchain/agents/agent.py", line 503, in _call
    next_step_output = self._take_next_step(
  File "/root/miniconda3/envs/visgpt/lib/python3.8/site-packages/langchain/agents/agent.py", line 420, in _take_next_step
    observation = tool.run(
  File "/root/miniconda3/envs/visgpt/lib/python3.8/site-packages/langchain/tools/base.py", line 71, in run
    raise e
  File "/root/miniconda3/envs/visgpt/lib/python3.8/site-packages/langchain/tools/base.py", line 68, in run
    observation = self._run(tool_input)
  File "/root/miniconda3/envs/visgpt/lib/python3.8/site-packages/langchain/agents/tools.py", line 17, in _run
    return self.func(tool_input)
  File "visual_chatgpt.py", line 164, in replace_part_of_image
    updated_image = self.inpainting(prompt=replace_with_txt, image=original_image, mask_image=mask_image).images[0]
  File "/root/miniconda3/envs/visgpt/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/visgpt/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py", line 770, in __call__
    raise ValueError("`mask_image` input cannot be undefined.")
ValueError: `mask_image` input cannot be undefined.

**Comment by sciart17** [comment]
I met the same error when trying to modify the image.

**Comment by congling** [comment]
After restarted and ran python at background, the error disappeared.

**Comment by Daryl149** [comment]
having the same issue, persists after restarting. 
What you you mean with running python at background?
