### ISSUE TITLE
ModuleNotFoundError: No module named 'gradio'

### ISSUE THREAD

**Issue by qingqingtina** [microsoft/visual-chatgpt#213]
I have installed the gradio module, but it still reporting errors as title

**Comment by Wang-Xiaodong1899** [comment]
Hi @qingqingtina, Can you provide more details? Such as the gradio version, and can you list and find the gradio via `pip list` in your conda environment.

**Comment by qingqingtina** [comment]
![image](https://user-images.githubusercontent.com/109122025/225661781-5e4b7e35-5b18-4c4a-93ca-1471c1066112.png)

**Comment by albertoecf** [comment]
Hey @Wang-Xiaodong1899 Thanks for all your help

 I've the same problem as @qingqingtina . I'm using mac m1 as well

(visgpt) Personal@MacBook visual-chatgpt % conda activate visgpt

(visgpt) Personal@MacBook visual-chatgpt % python visual_chatgpt.py --load ImageCaptioning_cpu,Text2Image_cpu

Traceback (most recent call last):
  File "visual_chatgpt.py", line 2, in <module>
    import gradio as gr
ImportError: No module named gradio

(visgpt) Personal@MacBook visual-chatgpt % pip list

<img width="353" alt="Captura de pantalla 2023-03-16 a las 17 09 56" src="https://user-images.githubusercontent.com/81099969/225682534-31e87e96-f1c7-4516-8370-5ec0d1f8ceec.png">

**Comment by wastu01** [comment]
I encounter this error before
I used "pip install gradio" in Mac M1 to fix it
https://copypaste.guru/WhereIsMyPythonModule/how-to-fix-modulenotfounderror-no-module-named-gradio

**Comment by albertoecf** [comment]
> I encounter this error before I used "pip install gradio" in Mac M1 to fix it https://copypaste.guru/WhereIsMyPythonModule/how-to-fix-modulenotfounderror-no-module-named-gradio

Hey @wastu01 thanks for answering! I've tried that (also pip uninstall gradio and install it again) but I receive the same problem 😢 

(visgpt) Personal@MacBook visual-chatgpt % python visual_chatgpt.py 
Traceback (most recent call last):
  File "visual_chatgpt.py", line 2, in <module>
    import gradio as gr
ImportError: No module named gradio

**Comment by wastu01** [comment]
I use pipenv for create environment.
according other issue for fixing problems.
may be try to remove and recreate environment ?
and to be sure check python version.

Hope that your fix problem soon.
I  get other problem in Mac M1 🥲

https://hackmd.io/@DCT/Microsoft-Visual-ChatGPT

**Comment by jenyzzn** [comment]
Try use "python3 visual_chatgpt.py" instead of python

**Comment by slightlycool** [comment]
> Try use "python3 visual_chatgpt.py" instead of python

great, solved!
