### ISSUE TITLE
Windows 11 errors: python visual_chatgpt.py --load ImageCaptioning_cpu,Text2Image_cpu

### ISSUE THREAD

**Issue by HabHab123** [microsoft/visual-chatgpt#217]
(visgpt) C:\Users\xxx\visual-chatgpt>python visual_chatgpt.py --load ImageCaptioning_cpu,Text2Image_cpu
Initializing VisualChatGPT, load_dict={'ImageCaptioning': 'cpu', 'Text2Image': 'cpu'}
Initializing ImageCaptioning to cpu
Initializing Text2Image to cpu
safety_checker\model.safetensors not found
Fetching 15 files: 100%|███████████████████████████████████████████████████████████████████████| 15/15 [00:00<?, ?it/s]
C:\Users\---\visual-chatgpt\visgpt\lib\site-packages\transformers\models\clip\feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
Running on local URL:  http://0.0.0.0:7868

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "C:\Users\xxx\visual-chatgpt\visgpt\lib\site-packages\gradio\routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\xxx\visual-chatgpt\visgpt\lib\site-packages\gradio\blocks.py", line 1032, in process_api
    result = await self.call_function(
  File "C:\Users\xxx\visual-chatgpt\visgpt\lib\site-packages\gradio\blocks.py", line 844, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\xxx\visual-chatgpt\visgpt\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\xxx\visual-chatgpt\visgpt\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\xxx\visual-chatgpt\visgpt\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "visual_chatgpt.py", line 847, in run_text
    self.agent.memory.buffer = cut_dialogue_history(self.agent.memory.buffer, keep_last_n_words=500)
  File "pydantic\main.py", line 357, in pydantic.main.BaseModel.__setattr__
ValueError: "ConversationBufferMemory" object has no field "buffer"

I am able to open the localhost , but i cant type having no results and also when i upload an image it gives an error too

I am using python 3.8.5 and i do not know how to solve it , can anyone help??

**Comment by AI-Robot-Morris** [comment]
THIS IS "GPU" training tool, 
BUY you ALL use CPU, I guess you may try colab than use cpu to run this.

**Comment by shengming-yin** [comment]
Hi @HabHab123  It seems like a problem of langchain version, and you can fix it by pip install langchain==0.0.101. Thanks!

**Comment by HabHab123** [comment]
thank you @shengming-yin it has worked.

@AI-Robot-Morris I will try it on as well , thank you

**Comment by shengming-yin** [comment]
Thanks~
