### ISSUE TITLE
ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by renaissancerachel** [microsoft/visual-chatgpt#220]
### Received error message:
`ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-17-f2e3ac98573b> in <module>
----> 1 from visual_chatgpt import *

~/miniconda3/envs/VisualChatGPT/visual-chatgpt/visual_chatgpt.py in <module>
      2 import gradio as gr
      3 import random
----> 4 import torch
      5 import cv2
      6 import re

ModuleNotFoundError: No module named 'torch'`

### Things I did to troubleshoot:
Tried:
```
!which python
!pip list | grep torch
```

And got back:
```
/Users/.../miniconda3/envs/VisualChatGPT/bin/python
open-clip-torch         2.16.0
torch                   1.12.1
torchmetrics            0.11.4
torchvision             0.13.1
```

Based off of reading other issues in this repo, I ran:
`pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url`

and also tried: 
`conda install pytorch==1.12.1 torchvision==0.13.1 cudatoolkit=11.6 -c pytorch -c conda-forge`

Not sure what else to try!

**Comment by renaissancerachel** [comment]
In case it's helpful, here are all the libraries I have installed when I run `conda list`:
```
# Name                    Version                   Build  Channel
absl-py                   1.4.0                    pypi_0    pypi
accelerate                0.17.1                   pypi_0    pypi
addict                    2.4.0                    pypi_0    pypi
aiofiles                  23.1.0                   pypi_0    pypi
aiohttp                   3.8.4                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
albumentations            1.3.0                    pypi_0    pypi
altair                    4.2.2                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
anyio                     3.6.2                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     22.2.0                   pypi_0    pypi
basicsr                   1.4.2                    pypi_0    pypi
blinker                   1.5                      pypi_0    pypi
braceexpand               0.1.7                    pypi_0    pypi
bzip2                     1.0.8                h1de35cc_0  
ca-certificates           2023.01.10           hecd8cb5_0  
cachetools                5.3.0                    pypi_0    pypi
certifi                   2022.12.7       py310hecd8cb5_0  
charset-normalizer        3.1.0                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
coloredlogs               15.0.1                   pypi_0    pypi
contourpy                 1.0.7                    pypi_0    pypi
controlnet-aux            0.0.1                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
dataclasses-json          0.5.7                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
diffusers                 0.14.0                   pypi_0    pypi
einops                    0.6.0                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
fastapi                   0.94.1                   pypi_0    pypi
ffmpy                     0.3.0                    pypi_0    pypi
filelock                  3.10.0                   pypi_0    pypi
flatbuffers               23.3.3                   pypi_0    pypi
fonttools                 4.39.2                   pypi_0    pypi
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2023.3.0                 pypi_0    pypi
ftfy                      6.1.1                    pypi_0    pypi
future                    0.18.3                   pypi_0    pypi
gitdb                     4.0.10                   pypi_0    pypi
gitpython                 3.1.31                   pypi_0    pypi
google-auth               2.16.2                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
gradio                    3.20.1                   pypi_0    pypi
greenlet                  2.0.2                    pypi_0    pypi
grpcio                    1.51.3                   pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
httpcore                  0.16.3                   pypi_0    pypi
httpx                     0.23.3                   pypi_0    pypi
huggingface-hub           0.13.2                   pypi_0    pypi
humanfriendly             10.0                     pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imageio                   2.26.0                   pypi_0    pypi
imageio-ffmpeg            0.4.8                    pypi_0    pypi
importlib-metadata        6.0.0                    pypi_0    pypi
invisible-watermark       0.1.5                    pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
jsonschema                4.17.3                   pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
kornia                    0.6.10                   pypi_0    pypi
langchain                 0.0.101                  pypi_0    pypi
lazy-loader               0.1                      pypi_0    pypi
libffi                    3.4.2                hecd8cb5_6  
linkify-it-py             2.0.0                    pypi_0    pypi
lmdb                      1.4.0                    pypi_0    pypi
markdown                  3.4.1                    pypi_0    pypi
markdown-it-py            2.2.0                    pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
marshmallow               3.19.0                   pypi_0    pypi
marshmallow-enum          1.5.1                    pypi_0    pypi
matplotlib                3.7.1                    pypi_0    pypi
mdit-py-plugins           0.3.3                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
ncurses                   6.4                  hcec6c5f_0  
networkx                  3.0                      pypi_0    pypi
numpy                     1.24.2                   pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
omegaconf                 2.3.0                    pypi_0    pypi
onnx                      1.13.1                   pypi_0    pypi
onnxruntime               1.14.1                   pypi_0    pypi
open-clip-torch           2.16.0                   pypi_0    pypi
openai                    0.27.2                   pypi_0    pypi
opencv-python             4.7.0.72                 pypi_0    pypi
opencv-python-headless    4.7.0.72                 pypi_0    pypi
openssl                   1.1.1t               hca72f7f_0  
orjson                    3.8.7                    pypi_0    pypi
packaging                 23.0                     pypi_0    pypi
pandas                    1.5.3                    pypi_0    pypi
pillow                    9.4.0                    pypi_0    pypi
pip                       23.0.1          py310hecd8cb5_0  
prettytable               3.6.0                    pypi_0    pypi
protobuf                  3.20.3                   pypi_0    pypi
psutil                    5.9.4                    pypi_0    pypi
pyarrow                   11.0.0                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycryptodome              3.17                     pypi_0    pypi
pydantic                  1.10.6                   pypi_0    pypi
pydeck                    0.8.0                    pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pygments                  2.14.0                   pypi_0    pypi
pympler                   1.0.1                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyrsistent                0.19.3                   pypi_0    pypi
python                    3.10.9               h218abb5_2  
python-dateutil           2.8.2                    pypi_0    pypi
python-multipart          0.0.6                    pypi_0    pypi
pytz                      2022.7.1                 pypi_0    pypi
pytz-deprecation-shim     0.1.0.post0              pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
qudida                    0.0.4                    pypi_0    pypi
readline                  8.2                  hca72f7f_0  
regex                     2022.10.31               pypi_0    pypi
requests                  2.28.2                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rfc3986                   1.5.0                    pypi_0    pypi
rich                      13.3.2                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
safetensors               0.3.0                    pypi_0    pypi
scikit-image              0.20.0                   pypi_0    pypi
scikit-learn              1.2.2                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
semver                    2.13.0                   pypi_0    pypi
sentencepiece             0.1.97                   pypi_0    pypi
setuptools                65.6.3          py310hecd8cb5_0  
six                       1.16.0                   pypi_0    pypi
smmap                     5.0.0                    pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
sqlalchemy                1.4.46                   pypi_0    pypi
sqlite                    3.41.1               h6c40b1e_0  
starlette                 0.26.1                   pypi_0    pypi
streamlit                 1.20.0                   pypi_0    pypi
sympy                     1.11.1                   pypi_0    pypi
tb-nightly                2.13.0a20230316          pypi_0    pypi
tenacity                  8.2.2                    pypi_0    pypi
tensorboard               2.12.0                   pypi_0    pypi
tensorboard-data-server   0.7.0                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
test-tube                 0.7.5                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2023.3.15                pypi_0    pypi
timm                      0.6.12                   pypi_0    pypi
tk                        8.6.12               h5d9f67b_0  
tokenizers                0.13.2                   pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
toolz                     0.12.0                   pypi_0    pypi
torch                     1.12.1                   pypi_0    pypi
torchmetrics              0.11.4                   pypi_0    pypi
torchvision               0.13.1                   pypi_0    pypi
tornado                   6.2                      pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
transformers              4.27.1                   pypi_0    pypi
typing-extensions         4.5.0                    pypi_0    pypi
typing-inspect            0.8.0                    pypi_0    pypi
tzdata                    2022.7                   pypi_0    pypi
tzlocal                   4.2                      pypi_0    pypi
uc-micro-py               1.0.1                    pypi_0    pypi
urllib3                   1.26.15                  pypi_0    pypi
uvicorn                   0.21.1                   pypi_0    pypi
validators                0.20.0                   pypi_0    pypi
wcwidth                   0.2.6                    pypi_0    pypi
webdataset                0.2.43                   pypi_0    pypi
websockets                10.4                     pypi_0    pypi
werkzeug                  2.2.3                    pypi_0    pypi
wheel                     0.38.4          py310hecd8cb5_0  
xz                        5.2.10               h6c40b1e_1  
yapf                      0.32.0                   pypi_0    pypi
yarl                      1.8.2                    pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h4dc903c_0  
```

**Comment by renaissancerachel** [comment]
I'm on Python 3.10.9

**Comment by 23kcarlson** [comment]
Try using 
`python -m pip install -r requirements.txt `
instead of
`pip install -r requirements.txt`

**Comment by renaissancerachel** [comment]
Thanks, @23kcarlson! Unfortunately, I'm still getting the same error message.

**Comment by synpore** [comment]
python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/zf/bnmb_frs0pj3pdzxyc15nxjr0000gp/T/pip-install-png5legm/basicsr_f3c96e2bac254f679073864f3c30b12a/setup.py", line 8, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]

"I have encountered the same problem."
