### ISSUE TITLE
Potential NSFW content was detected in one or more images. A black image will be returned instead. 

### ISSUE THREAD

**Issue by michaelchensz** [microsoft/visual-chatgpt#236]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
![1679043636734](https://user-images.githubusercontent.com/5894223/225859461-66cba495-ffd8-4c09-9040-4ef7923036bd.png)

Any suggestion?

**Comment by michaelchensz** [comment]
another issue. After an image is generated,  to draw another image, then error happened.  
> Entering new AgentExecutor chain...
 Yes
Action: Generate Image From User Input Text
  0%|                                                                                           | 0/50 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\mcsz\Miniconda3\envs\visgpt\lib\site-packages\gradio\routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\mcsz\Miniconda3\envs\visgpt\lib\site-packages\gradio\blocks.py", line 1032, in process_api
    result = await self.call_function(
  File "C:\Users\mcsz\Miniconda3\envs\visgpt\lib\site-packages\gradio\blocks.py", line 844, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\mcsz\Miniconda3\envs\visgpt\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\mcsz\Miniconda3\envs\visgpt\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\mcsz\Miniconda3\envs\visgpt\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "visual_chatgpt.py", line 848, in run_text
    res = self.agent({"input": text})
  File "C:\Users\mcsz\Miniconda3\envs\visgpt\lib\site-packages\langchain\chains\base.py", line 168, in __call__
    raise e
  File "C:\Users\mcsz\Miniconda3\envs\visgpt\lib\site-packages\langchain\chains\base.py", line 165, in __call__
    outputs = self._call(inputs)
  File "C:\Users\mcsz\Miniconda3\envs\visgpt\lib\site-packages\langchain\agents\agent.py", line 503, in _call
    next_step_output = self._take_next_step(
  File "C:\Users\mcsz\Miniconda3\envs\visgpt\lib\site-packages\langchain\agents\agent.py", line 420, in _take_next_step
    observation = tool.run(
  File "C:\Users\mcsz\Miniconda3\envs\visgpt\lib\site-packages\langchain\tools\base.py", line 71, in run
    raise e
  File "C:\Users\mcsz\Miniconda3\envs\visgpt\lib\site-packages\langchain\tools\base.py", line 68, in run
    observation = self._run(tool_input)
  File "C:\Users\mcsz\Miniconda3\envs\visgpt\lib\site-packages\langchain\agents\tools.py", line 17, in _run
    return self.func(tool_input)
  File "visual_chatgpt.py", line 239, in inference
    image = self.pipe(prompt, negative_prompt=self.n_prompt).images[0]
  File "C:\Users\mcsz\Miniconda3\envs\visgpt\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\mcsz\Miniconda3\envs\visgpt\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 667, in __call__
    noise_pred = self.unet(
  File "C:\Users\mcsz\Miniconda3\envs\visgpt\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mcsz\Miniconda3\envs\visgpt\lib\site-packages\diffusers\models\unet_2d_condition.py", line 576, in forward
    sample = self.conv_in(sample)
  File "C:\Users\mcsz\Miniconda3\envs\visgpt\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mcsz\Miniconda3\envs\visgpt\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\mcsz\Miniconda3\envs\visgpt\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

**Comment by michaelchensz** [comment]
according to https://github.com/CompVis/stable-diffusion/issues/239, it may explain why this issue happens.

"If you have a Nvidia GTX series GPU, the output images maybe entirely green in color. This is because GTX series do not support half precision calculation, which is the default mode of calculation in this repository. To overcome the issue, use the --precision full argument. The downside is that it will lead to higher GPU VRAM usage."

**Comment by zhy668** [comment]
> according to [CompVis/stable-diffusion#239](https://github.com/CompVis/stable-diffusion/issues/239), it may explain why this issue happens.
> 
> "If you have a Nvidia GTX series GPU, the output images maybe entirely green in color. This is because GTX series do not support half precision calculation, which is the default mode of calculation in this repository. To overcome the issue, use the --precision full argument. The downside is that it will lead to higher GPU VRAM usage."
How to add --precision full argument？

**Comment by alexanderbkl** [comment]
Having the same issue and got rate limited, maybe NSFW triggered and OpenAI banned the organization?

**Comment by alexanderbkl** [comment]
> 

Probably that, fixed after some time by itself.

**Comment by 3Diva** [comment]
I'm getting this same issue now - is there a fix for this?
