### ISSUE TITLE
the session window did not respond

### ISSUE THREAD

**Issue by isencher** [microsoft/visual-chatgpt#241]
When I submitted the session, the session window did not respond, but the terminal showed:
**> Entering new AgentExecutor chain...**
Retrying langchain.llms.openai.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))).
Retrying langchain.llms.openai.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))).
Retrying langchain.llms.openai.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))).
Retrying langchain.llms.openai.completion_with_retry.<locals>._completion_with_retry in 8.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))).
Retrying langchain.llms.openai.completion_with_retry.<locals>._completion_with_retry in 10.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))).
Traceback (most recent call last):
  File "E:\dev\visual-chatgpt\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "E:\dev\visual-chatgpt\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "E:\dev\visual-chatgpt\lib\site-packages\urllib3\connection.py", line 369, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "E:\dev\visual-chatgpt\lib\site-packages\urllib3\connection.py", line 504, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "E:\dev\visual-chatgpt\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "E:\dev\visual-chatgpt\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "D:\programs\python\python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\programs\python\python38\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "D:\programs\python\python38\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\dev\visual-chatgpt\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "E:\dev\visual-chatgpt\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "E:\dev\visual-chatgpt\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "E:\dev\visual-chatgpt\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "E:\dev\visual-chatgpt\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\dev\visual-chatgpt\lib\site-packages\openai\api_requestor.py", line 516, in request_raw
    result = _thread_context.session.request(
  File "E:\dev\visual-chatgpt\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\dev\visual-chatgpt\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\dev\visual-chatgpt\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\dev\visual-chatgpt\lib\site-packages\gradio\routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\dev\visual-chatgpt\lib\site-packages\gradio\blocks.py", line 1032, in process_api
    result = await self.call_function(
  File "E:\dev\visual-chatgpt\lib\site-packages\gradio\blocks.py", line 844, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\dev\visual-chatgpt\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\dev\visual-chatgpt\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\dev\visual-chatgpt\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "visual_chatgpt.py", line 848, in run_text
    res = self.agent({"input": text})
  File "E:\dev\visual-chatgpt\lib\site-packages\langchain\chains\base.py", line 168, in __call__
    raise e
  File "E:\dev\visual-chatgpt\lib\site-packages\langchain\chains\base.py", line 165, in __call__
    outputs = self._call(inputs)
  File "E:\dev\visual-chatgpt\lib\site-packages\langchain\agents\agent.py", line 503, in _call
    next_step_output = self._take_next_step(
  File "E:\dev\visual-chatgpt\lib\site-packages\langchain\agents\agent.py", line 406, in _take_next_step
    output = self.agent.plan(intermediate_steps, **inputs)
  File "E:\dev\visual-chatgpt\lib\site-packages\langchain\agents\agent.py", line 102, in plan
    action = self._get_next_action(full_inputs)
  File "E:\dev\visual-chatgpt\lib\site-packages\langchain\agents\agent.py", line 63, in _get_next_action
    full_output = self.llm_chain.predict(**full_inputs)
  File "E:\dev\visual-chatgpt\lib\site-packages\langchain\chains\llm.py", line 155, in predict
    return self(kwargs)[self.output_key]
  File "E:\dev\visual-chatgpt\lib\site-packages\langchain\chains\base.py", line 168, in __call__
    raise e
  File "E:\dev\visual-chatgpt\lib\site-packages\langchain\chains\base.py", line 165, in __call__
    outputs = self._call(inputs)
  File "E:\dev\visual-chatgpt\lib\site-packages\langchain\chains\llm.py", line 135, in _call
    return self.apply([known_values])[0]
  File "E:\dev\visual-chatgpt\lib\site-packages\langchain\chains\llm.py", line 117, in apply
    response = self.generate(input_list)
  File "E:\dev\visual-chatgpt\lib\site-packages\langchain\chains\llm.py", line 59, in generate
    response = self.llm.generate(prompts, stop=stop)
  File "E:\dev\visual-chatgpt\lib\site-packages\langchain\llms\base.py", line 128, in generate
    raise e
  File "E:\dev\visual-chatgpt\lib\site-packages\langchain\llms\base.py", line 125, in generate
    output = self._generate(prompts, stop=stop)
  File "E:\dev\visual-chatgpt\lib\site-packages\langchain\llms\openai.py", line 274, in _generate
    response = completion_with_retry(self, prompt=_prompts, **params)
  File "E:\dev\visual-chatgpt\lib\site-packages\langchain\llms\openai.py", line 98, in completion_with_retry
    return _completion_with_retry(**kwargs)
  File "E:\dev\visual-chatgpt\lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "E:\dev\visual-chatgpt\lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "E:\dev\visual-chatgpt\lib\site-packages\tenacity\__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "E:\dev\visual-chatgpt\lib\site-packages\tenacity\__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "D:\programs\python\python38\lib\concurrent\futures\_base.py", line 437, in result
    return self.__get_result()
  File "D:\programs\python\python38\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
  File "E:\dev\visual-chatgpt\lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "E:\dev\visual-chatgpt\lib\site-packages\langchain\llms\openai.py", line 96, in _completion_with_retry
    return llm.client.create(**kwargs)
  File "E:\dev\visual-chatgpt\lib\site-packages\openai\api_resources\completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "E:\dev\visual-chatgpt\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "E:\dev\visual-chatgpt\lib\site-packages\openai\api_requestor.py", line 216, in request
    result = self.request_raw(
  File "E:\dev\visual-chatgpt\lib\site-packages\openai\api_requestor.py", line 528, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

**Comment by Aricling** [comment]
I've got the same problem, anyone can help me with it? I'd very much appreciatie it!

**Comment by isencher** [comment]
This problem is the same as #67, and the provided solution is to specify a proxy in the terminal. However, how can I specify a proxy in the terminal?
