### ISSUE TITLE
Extra fields not permitted from pydantic 

### ISSUE THREAD

**Issue by kyocwn** [microsoft/visual-chatgpt#259]
Hi,

When I am running the following script:
python visual_chatgpt.py --load ImageCaptioning_cpu, Text2Image_cpu

I see some errors like follows:

Initializing VisualChatGPT, load_dict={'ImageCaptioning': 'cpu', 'Text2Image': 'cpu'}
Traceback (most recent call last):
  File "visual_chatgpt.py", line 885, in <module>
    bot = ConversationBot(load_dict=load_dict)
  File "visual_chatgpt.py", line 824, in __init__
    self.memory = ConversationBufferMemory(memory_key="chat_history", output_key='output')
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ConversationBufferMemory
output_key
  extra fields not permitted (type=value_error.extra)
  
 Can anyone help? What shall I do to fix this problem?

**Comment by superdog125** [comment]
I met too.

**Comment by haizi110** [comment]
I met too,any answer?
