### ISSUE TITLE
Error: import cv2 with current requirements.txt

### ISSUE THREAD

**Issue by adastrali** [microsoft/visual-chatgpt#262]
Traceback (most recent call last):
  File "visual_chatgpt.py", line 6, in <module>
    import cv2
  File "/home/xx/miniconda3/envs/visgpt/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/xx/miniconda3/envs/visgpt/lib/python3.8/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/home/xx/miniconda3/envs/visgpt/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by hongcongjin** [comment]
apt install libgl1-mesa-glx
安装这个就可以解决
