### ISSUE TITLE
RuntimeError: GET was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by dadaxxxx** [microsoft/visual-chatgpt#283]
have someone encountered any such problems

Action: Generate Image From User Input Text
  0%|                                                                                                       | 0/50 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/ps/anaconda3/envs/visgpt/lib/python3.8/site-packages/gradio/routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/ps/anaconda3/envs/visgpt/lib/python3.8/site-packages/gradio/blocks.py", line 1032, in process_api
    result = await self.call_function(
  File "/home/ps/anaconda3/envs/visgpt/lib/python3.8/site-packages/gradio/blocks.py", line 844, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/ps/anaconda3/envs/visgpt/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/ps/anaconda3/envs/visgpt/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/ps/anaconda3/envs/visgpt/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "visual_chatgpt.py", line 850, in run_text
    res = self.agent({"input": text})
  File "/home/ps/anaconda3/envs/visgpt/lib/python3.8/site-packages/langchain/chains/base.py", line 168, in __call__
    raise e
  File "/home/ps/anaconda3/envs/visgpt/lib/python3.8/site-packages/langchain/chains/base.py", line 165, in __call__
    outputs = self._call(inputs)
  File "/home/ps/anaconda3/envs/visgpt/lib/python3.8/site-packages/langchain/agents/agent.py", line 503, in _call
    next_step_output = self._take_next_step(
  File "/home/ps/anaconda3/envs/visgpt/lib/python3.8/site-packages/langchain/agents/agent.py", line 420, in _take_next_step
    observation = tool.run(
  File "/home/ps/anaconda3/envs/visgpt/lib/python3.8/site-packages/langchain/tools/base.py", line 71, in run
    raise e
  File "/home/ps/anaconda3/envs/visgpt/lib/python3.8/site-packages/langchain/tools/base.py", line 68, in run
    observation = self._run(tool_input)
  File "/home/ps/anaconda3/envs/visgpt/lib/python3.8/site-packages/langchain/agents/tools.py", line 17, in _run
    return self.func(tool_input)
  File "visual_chatgpt.py", line 241, in inference
    image = self.pipe(prompt, negative_prompt=self.n_prompt).images[0]
  File "/home/ps/anaconda3/envs/visgpt/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ps/anaconda3/envs/visgpt/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 667, in __call__
    noise_pred = self.unet(
  File "/home/ps/anaconda3/envs/visgpt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ps/anaconda3/envs/visgpt/lib/python3.8/site-packages/diffusers/models/unet_2d_condition.py", line 576, in forward
    sample = self.conv_in(sample)
  File "/home/ps/anaconda3/envs/visgpt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ps/anaconda3/envs/visgpt/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/ps/anaconda3/envs/visgpt/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: GET was unable to find an engine to execute this computation

**Comment by mayank010698** [comment]
Facing the same issue.

**Comment by JKHenry520** [comment]
Facing the same issue.

**Comment by gusatbuzz** [comment]
+1

**Comment by Taoww21480** [comment]
降低torch版本，多半是由于torch==2.0.0,使用如下命令（这是我自己解决的方式，仅供参考）：
pip install torch==1.13.0 torchvision==0.14.0 torchaudio==0.13.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
降低torch版本同时把torchvision和torchaudio版本都降低，此外，可以查看自己的torch对应的cuda版本
print(torch.__version__)  
print(torch.version.cuda)  
去灌官网上找匹配的torch安装

**Comment by zongh5a** [comment]
可以放到CPU运算，之后再加载回GPU继续
