### ISSUE TITLE
ValueError: "ConversationBufferMemory" object has no field "buffer"

### ISSUE THREAD

**Issue by cometbus** [microsoft/visual-chatgpt#310]
I'm getting this error I'm running wsl2 ubuntu I have cuda and nvida drivers, all requirements installed
running on local URL:  http://0.0.0.0:1015

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/root/openai-quickstart-python/myenv/lib/python3.10/site-packages/gradio/routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/openai-quickstart-python/myenv/lib/python3.10/site-packages/gradio/blocks.py", line 1032, in process_api
    result = await self.call_function(
  File "/root/openai-quickstart-python/myenv/lib/python3.10/site-packages/gradio/blocks.py", line 844, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/openai-quickstart-python/myenv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/openai-quickstart-python/myenv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/openai-quickstart-python/myenv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/visual-chatgpt/visual_chatgpt.py", line 1014, in run_text
    self.agent.memory.buffer = cut_dialogue_history(self.agent.memory.buffer, keep_last_n_words=500)
  File "pydantic/main.py", line 357, in pydantic.main.BaseModel.__setattr__
ValueError: "ConversationBufferMemory" object has no field "buffer"

**Comment by Bean95zx** [comment]
i found the solution by re-install the langchain-0.0.101 in this issue(issues/281). i wish it can help you
