### ISSUE TITLE
Exception occurs when I try to generate image

### ISSUE THREAD

**Issue by mengdalida** [microsoft/visual-chatgpt#332]
Traceback (most recent call last):                                                                                              
  File "C:\Users\xingzi\anaconda3\envs\visgpt\lib\site-packages\gradio\routes.py", line 384, in run_predict                     
    output = await app.get_blocks().process_api(                                                                                
  File "C:\Users\xingzi\anaconda3\envs\visgpt\lib\site-packages\gradio\blocks.py", line 1032, in process_api                    
    result = await self.call_function(                                                                                          
  File "C:\Users\xingzi\anaconda3\envs\visgpt\lib\site-packages\gradio\blocks.py", line 844, in call_function                   
    prediction = await anyio.to_thread.run_sync(                                                                                
  File "C:\Users\xingzi\anaconda3\envs\visgpt\lib\site-packages\anyio\to_thread.py", line 31, in run_sync                       
    return await get_asynclib().run_sync_in_worker_thread(                                                                      
  File "C:\Users\xingzi\anaconda3\envs\visgpt\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_th
read                                                                                                                            
    return await future                                                                                                         
  File "C:\Users\xingzi\anaconda3\envs\visgpt\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run                  
    result = context.run(func, *args)                                                                                           
  File "visual_chatgpt.py", line 866, in run_text                                                                               
    res = self.agent({"input": text})                                                                                           
  File "C:\Users\xingzi\anaconda3\envs\visgpt\lib\site-packages\langchain\chains\base.py", line 168, in __call__                
    raise e                                                                                                                     
  File "C:\Users\xingzi\anaconda3\envs\visgpt\lib\site-packages\langchain\chains\base.py", line 165, in __call__                
    outputs = self._call(inputs)                                                                                                
  File "C:\Users\xingzi\anaconda3\envs\visgpt\lib\site-packages\langchain\agents\agent.py", line 503, in _call                  
    next_step_output = self._take_next_step(                                                                                    
  File "C:\Users\xingzi\anaconda3\envs\visgpt\lib\site-packages\langchain\agents\agent.py", line 420, in _take_next_step        
    observation = tool.run(                                                                                                     
  File "C:\Users\xingzi\anaconda3\envs\visgpt\lib\site-packages\langchain\tools\base.py", line 71, in run                       
    raise e                                                                                                                     
  File "C:\Users\xingzi\anaconda3\envs\visgpt\lib\site-packages\langchain\tools\base.py", line 68, in run                       
    observation = self._run(tool_input)                                                                                         
  File "C:\Users\xingzi\anaconda3\envs\visgpt\lib\site-packages\langchain\agents\tools.py", line 17, in _run                    
    return self.func(tool_input)                                                                                                
  File "visual_chatgpt.py", line 255, in inference                                                                              
    image = self.pipe(prompt, negative_prompt=self.n_prompt).images[0]                                                          
  File "C:\Users\xingzi\anaconda3\envs\visgpt\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context      
    return func(*args, **kwargs)                                                                                                
  File "C:\Users\xingzi\anaconda3\envs\visgpt\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.p
y", line 667, in __call__                                                                                                       
    noise_pred = self.unet(                                                                                                     
  File "C:\Users\xingzi\anaconda3\envs\visgpt\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl           
    return forward_call(*input, **kwargs)                                                                                       
  File "C:\Users\xingzi\anaconda3\envs\visgpt\lib\site-packages\diffusers\models\unet_2d_condition.py", line 582, in forward    
    sample, res_samples = downsample_block(                                                                                     
  File "C:\Users\xingzi\anaconda3\envs\visgpt\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl           
    return forward_call(*input, **kwargs)                                                                                       
  File "C:\Users\xingzi\anaconda3\envs\visgpt\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 836, in forward       
    hidden_states = resnet(hidden_states, temb)                                                                                 
  File "C:\Users\xingzi\anaconda3\envs\visgpt\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl           
    return forward_call(*input, **kwargs)                                                                                       
  File "C:\Users\xingzi\anaconda3\envs\visgpt\lib\site-packages\diffusers\models\resnet.py", line 540, in forward               
    hidden_states = self.norm1(hidden_states)                                                                                   
  File "C:\Users\xingzi\anaconda3\envs\visgpt\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl           
    return forward_call(*input, **kwargs)                                                                                       
  File "C:\Users\xingzi\anaconda3\envs\visgpt\lib\site-packages\torch\nn\modules\normalization.py", line 273, in forward        
    return F.group_norm(                                                                                                        
  File "C:\Users\xingzi\anaconda3\envs\visgpt\lib\site-packages\torch\nn\functional.py", line 2528, in group_norm               
    return torch.group_norm(input, num_groups, weight, bias, eps, torch.backends.cudnn.enabled)                                 
RuntimeError

**Comment by wyatthomg** [comment]
use linux easier than window
