### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by vpegasus** [microsoft/visual-chatgpt#4]
```bash
> Entering new AgentExecutor chain...
 Yes
Action: Generate Image From User Input Text
Action Input: cute cat/opt/conda/envs/visgpt/lib/python3.8/site-packages/transformers/generation/utils.py:1186: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation)
  warnings.warn(
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Traceback (most recent call last):
  File "/opt/conda/envs/visgpt/lib/python3.8/site-packages/gradio/routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "/opt/conda/envs/visgpt/lib/python3.8/site-packages/gradio/blocks.py", line 1032, in process_api
    result = await self.call_function(
  File "/opt/conda/envs/visgpt/lib/python3.8/site-packages/gradio/blocks.py", line 844, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/opt/conda/envs/visgpt/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/conda/envs/visgpt/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/envs/visgpt/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "visual_chatgpt.py", line 908, in run_text
    res = self.agent({"input": text})
  File "/opt/conda/envs/visgpt/lib/python3.8/site-packages/langchain/chains/base.py", line 168, in __call__
    raise e
  File "/opt/conda/envs/visgpt/lib/python3.8/site-packages/langchain/chains/base.py", line 165, in __call__
    outputs = self._call(inputs)
  File "/opt/conda/envs/visgpt/lib/python3.8/site-packages/langchain/agents/agent.py", line 503, in _call
    next_step_output = self._take_next_step(
  File "/opt/conda/envs/visgpt/lib/python3.8/site-packages/langchain/agents/agent.py", line 420, in _take_next_step
    observation = tool.run(
  File "/opt/conda/envs/visgpt/lib/python3.8/site-packages/langchain/tools/base.py", line 71, in run
    raise e
  File "/opt/conda/envs/visgpt/lib/python3.8/site-packages/langchain/tools/base.py", line 68, in run
    observation = self._run(tool_input)
  File "/opt/conda/envs/visgpt/lib/python3.8/site-packages/langchain/agents/tools.py", line 17, in _run
    return self.func(tool_input)
  File "visual_chatgpt.py", line 198, in inference
    refined_text = self.text_refine_gpt2_pipe(text)[0]["generated_text"]
  File "/opt/conda/envs/visgpt/lib/python3.8/site-packages/transformers/pipelines/text_generation.py", line 210, in __call__
    return super().__call__(text_inputs, **kwargs)
  File "/opt/conda/envs/visgpt/lib/python3.8/site-packages/transformers/pipelines/base.py", line 1084, in __call__
    return self.run_single(inputs, preprocess_params, forward_params, postprocess_params)
  File "/opt/conda/envs/visgpt/lib/python3.8/site-packages/transformers/pipelines/base.py", line 1091, in run_single
    model_outputs = self.forward(model_inputs, **forward_params)
  File "/opt/conda/envs/visgpt/lib/python3.8/site-packages/transformers/pipelines/base.py", line 992, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
  File "/opt/conda/envs/visgpt/lib/python3.8/site-packages/transformers/pipelines/text_generation.py", line 252, in _forward
    generated_sequence = self.model.generate(input_ids=input_ids, attention_mask=attention_mask, **generate_kwargs)
  File "/opt/conda/envs/visgpt/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/visgpt/lib/python3.8/site-packages/transformers/generation/utils.py", line 1242, in generate
    and torch.sum(inputs_tensor[:, -1] == generation_config.pad_token_id) > 0
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

cuda version: 
```bash
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0
```

more information: as I only have two gpus (40g per gpu), I changed the device number:

<img width="810" alt="截屏2023-03-09下午3 43 47" src="https://user-images.githubusercontent.com/22723154/223956589-78957edb-0896-487b-8138-f88ea5cf771c.png">

how to fix?

**Comment by CODINNLG** [comment]
Hi, have you run the command ``pip install -r requirement.txt``? Besides, you can check if your CUDA version matches the torch version. For more reference: [https://stackoverflow.com/questions/65739700/pytorch-cuda-error-no-kernel-image-is-available-for-execution-on-the-device-on](https://stackoverflow.com/questions/65739700/pytorch-cuda-error-no-kernel-image-is-available-for-execution-on-the-device-on)

**Comment by vpegasus** [comment]
```
conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch
```
this works me
