### ISSUE TITLE
运行成功，但打开http://0.0.0.0:7860时提示以下错误，请大家帮忙解决一下！

### ISSUE THREAD

**Issue by IssacaLaw** [microsoft/visual-chatgpt#71]
![image](https://user-images.githubusercontent.com/71266344/224482538-bd10b440-38df-4edd-9830-096d143cd415.png)
网址为 http://0.0.0.0:7860/ 的网页可能暂时无法连接，或者它已永久性地移动到了新网址

**Comment by K-tang-mkv** [comment]
@IssacaLaw  你是在本地运行的吗，如果是服务器的话是不能直接这样访问的，要么设置`--share=True`, 或者转发到本地端口进行访问

**Comment by K-tang-mkv** [comment]
@IssacaLaw 或者你可以参考一下我的colab notebook [https://github.com/K-tang-mkv/visual-chatgpt-googlecolab](https://github.com/K-tang-mkv/visual-chatgpt-googlecolab), 我在visual-chatgpt.py里修改最后一行的启动方式，使其能公共访问。
![Screen Shot 2023-03-11 at 7 57 59 PM](https://user-images.githubusercontent.com/59059785/224483002-c6e24f35-6d4a-4176-a387-8fe75b87627e.png)

**Comment by LiangSu8899** [comment]
想问下你们用的什么卡

**Comment by IssacaLaw** [comment]
> @IssacaLaw或者你可以参考一下我的colab notebook https://github.com/K-tang-mkv/visual-chatgpt-googlecolab，我在visual-chatgpt.py里修改最后一步的启动方式，使之能够公共访问。 ![屏幕截图 2023-03-11 下午 7 点 57 分 59 秒](https://user-images.githubusercontent.com/59059785/224483002-c6e24f35-6d4a-4176-a387-8fe75b87627e.png)

感谢回复，我是本地运行的，但是我按照你的958行的代码修改后，还是这个报错，是还有什么需要修改的吗？

**Comment by IssacaLaw** [comment]
> 想问下你们用的什么卡

我是用3090ti

**Comment by F4irytale** [comment]
请问window下apikey填在哪里

**Comment by IssacaLaw** [comment]
> 请问window下apikey填在哪里

在你的环境下的命令窗口下执行：set OPENAI_API_KEY={Your_Private_Openai_Key}

**Comment by EnthusiasticZ** [comment]
老哥问一下bash download.sh这一步你那边显示的什么？

**Comment by K-tang-mkv** [comment]
> > @IssacaLaw或者你可以参考一下我的colab notebook [https://github.com/K-tang-mkv/visual-chatgpt-googlecolab，我在visual-chatgpt.py里修改最后一步的启动方式，使之能够公共访问。](https://github.com/K-tang-mkv/visual-chatgpt-googlecolab%EF%BC%8C%E6%88%91%E5%9C%A8visual-chatgpt.py%E9%87%8C%E4%BF%AE%E6%94%B9%E6%9C%80%E5%90%8E%E4%B8%80%E6%AD%A5%E7%9A%84%E5%90%AF%E5%8A%A8%E6%96%B9%E5%BC%8F%EF%BC%8C%E4%BD%BF%E4%B9%8B%E8%83%BD%E5%A4%9F%E5%85%AC%E5%85%B1%E8%AE%BF%E9%97%AE%E3%80%82) ![屏幕截图 2023-03-11 下午 7 点 57 分 59 秒](https://user-images.githubusercontent.com/59059785/224483002-c6e24f35-6d4a-4176-a387-8fe75b87627e.png)
> 
> 感谢回复，我是本地运行的，但是我按照你的958行的代码修改后，还是这个报错，是还有什么需要修改的吗？

如果加了`share=True`，那你可以试下公共访问的网址，想知道公共网址也是报错吗？

**Comment by IssacaLaw** [comment]
> 老哥问一下bash download.sh这一步你那边显示的什么？

git界面，然后完成contronNet的下载，自动关闭界面。

**Comment by IssacaLaw** [comment]
> > > @IssacaLaw或者你可以参考一下我的colab notebook [https://github.com/K-tang-mkv/visual-chatgpt-googlecolab，我在visual-chatgpt.py里修改最后一步的启动方式，使之能够公共访问。](https://github.com/K-tang-mkv/visual-chatgpt-googlecolab%EF%BC%8C%E6%88%91%E5%9C%A8visual-chatgpt.py%E9%87%8C%E4%BF%AE%E6%94%B9%E6%9C%80%E5%90%8E%E4%B8%80%E6%AD%A5%E7%9A%84%E5%90%AF%E5%8A%A8%E6%96%B9%E5%BC%8F%EF%BC%8C%E4%BD%BF%E4%B9%8B%E8%83%BD%E5%A4%9F%E5%85%AC%E5%85%B1%E8%AE%BF%E9%97%AE%E3%80%82) ![屏幕截图 2023-03-11 下午 7 点 57 分 59 秒](https://user-images.githubusercontent.com/59059785/224483002-c6e24f35-6d4a-4176-a387-8fe75b87627e.png)
> > 
> > 
> > 感谢回复，我是本地运行的，但是我按照你的958行的代码修改后，还是这个报错，是还有什么需要修改的吗？
> 
> 如果加了`share=True`，那你可以试下公共访问的网址？

什么意思，不是进入它提供的url:http://0.0.0.0:7860/ 吗

**Comment by F4irytale** [comment]
把0.0.0.0改成localhost或者127.0.0.1

**Comment by 77LJH** [comment]
老哥，我在pip install -r requirement.txt这一步发现，下载第一个都特别慢，而且报错：
(visgpt) PS D:\IDM\IDM_download\压缩文件\visual-chatgpt-main\visual-chatgpt-main> pip install -r requirement.txt
Collecting torch==1.12.1
  Downloading torch-1.12.1-cp38-cp38-win_amd64.whl (161.9 MB)
     ━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/161.9 MB 26.9 kB/s eta 1:32:21
ERROR: Exception:
Traceback (most recent call last):
  File "D:\Anaconda\envs\visgpt\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "D:\Anaconda\envs\visgpt\lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "D:\Anaconda\envs\visgpt\lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "D:\Anaconda\envs\visgpt\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "D:\Anaconda\envs\visgpt\lib\http\client.py", line 459, in read
    n = self.readinto(b)
  File "D:\Anaconda\envs\visgpt\lib\http\client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "D:\Anaconda\envs\visgpt\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "D:\Anaconda\envs\visgpt\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "D:\Anaconda\envs\visgpt\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\visgpt\lib\site-packages\pip\_internal\cli\base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "D:\Anaconda\envs\visgpt\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "D:\Anaconda\envs\visgpt\lib\site-packages\pip\_internal\commands\install.py", line 419, in run
    requirement_set = resolver.resolve(
  File "D:\Anaconda\envs\visgpt\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "D:\Anaconda\envs\visgpt\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "D:\Anaconda\envs\visgpt\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "D:\Anaconda\envs\visgpt\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "D:\Anaconda\envs\visgpt\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "D:\Anaconda\envs\visgpt\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "D:\Anaconda\envs\visgpt\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "D:\Anaconda\envs\visgpt\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "D:\Anaconda\envs\visgpt\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "D:\Anaconda\envs\visgpt\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 297, in __init__
    super().__init__(
  File "D:\Anaconda\envs\visgpt\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "D:\Anaconda\envs\visgpt\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "D:\Anaconda\envs\visgpt\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "D:\Anaconda\envs\visgpt\lib\site-packages\pip\_internal\operations\prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "D:\Anaconda\envs\visgpt\lib\site-packages\pip\_internal\operations\prepare.py", line 536, in _prepare_linked_requirement
    local_file = unpack_url(
  File "D:\Anaconda\envs\visgpt\lib\site-packages\pip\_internal\operations\prepare.py", line 166, in unpack_url
    file = get_http_url(
  File "D:\Anaconda\envs\visgpt\lib\site-packages\pip\_internal\operations\prepare.py", line 107, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "D:\Anaconda\envs\visgpt\lib\site-packages\pip\_internal\network\download.py", line 147, in __call__
    for chunk in chunks:
  File "D:\Anaconda\envs\visgpt\lib\site-packages\pip\_internal\cli\progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "D:\Anaconda\envs\visgpt\lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "D:\Anaconda\envs\visgpt\lib\site-packages\pip\_vendor\urllib3\response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "D:\Anaconda\envs\visgpt\lib\site-packages\pip\_vendor\urllib3\response.py", line 587, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "D:\Anaconda\envs\visgpt\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "D:\Anaconda\envs\visgpt\lib\site-packages\pip\_vendor\urllib3\response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

**Comment by F4irytale** [comment]
> 老哥，我在pip install -r requirement.txt这一步发现，下载第一个都特别慢，而且报错： (visgpt) PS D:\IDM\IDM_download\压缩文件\visual-chatgpt-main\visual-chatgpt-main> pip install -r requirement.txt Collecting torch==1.12.1 Downloading torch-1.12.1-cp38-cp38-win_amd64.whl (161.9 MB) ━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/161.9 MB 26.9 kB/s eta 1:32:21 ERROR: Exception: Traceback (most recent call last): File "D:\Anaconda\envs\visgpt\lib\site-packages\pip_vendor\urllib3\response.py", line 438, in _error_catcher yield File "D:\Anaconda\envs\visgpt\lib\site-packages\pip_vendor\urllib3\response.py", line 561, in read data = self._fp_read(amt) if not fp_closed else b"" File "D:\Anaconda\envs\visgpt\lib\site-packages\pip_vendor\urllib3\response.py", line 527, in _fp_read return self._fp.read(amt) if amt is not None else self._fp.read() File "D:\Anaconda\envs\visgpt\lib\site-packages\pip_vendor\cachecontrol\filewrapper.py", line 90, in read data = self.__fp.read(amt) File "D:\Anaconda\envs\visgpt\lib\http\client.py", line 459, in read n = self.readinto(b) File "D:\Anaconda\envs\visgpt\lib\http\client.py", line 503, in readinto n = self.fp.readinto(b) File "D:\Anaconda\envs\visgpt\lib\socket.py", line 669, in readinto return self._sock.recv_into(b) File "D:\Anaconda\envs\visgpt\lib\ssl.py", line 1241, in recv_into return self.read(nbytes, buffer) File "D:\Anaconda\envs\visgpt\lib\ssl.py", line 1099, in read return self._sslobj.read(len, buffer) socket.timeout: The read operation timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "D:\Anaconda\envs\visgpt\lib\site-packages\pip_internal\cli\base_command.py", line 160, in exc_logging_wrapper status = run_func(*args) File "D:\Anaconda\envs\visgpt\lib\site-packages\pip_internal\cli\req_command.py", line 247, in wrapper return func(self, options, args) File "D:\Anaconda\envs\visgpt\lib\site-packages\pip_internal\commands\install.py", line 419, in run requirement_set = resolver.resolve( File "D:\Anaconda\envs\visgpt\lib\site-packages\pip_internal\resolution\resolvelib\resolver.py", line 92, in resolve result = self._result = resolver.resolve( File "D:\Anaconda\envs\visgpt\lib\site-packages\pip_vendor\resolvelib\resolvers.py", line 481, in resolve state = resolution.resolve(requirements, max_rounds=max_rounds) File "D:\Anaconda\envs\visgpt\lib\site-packages\pip_vendor\resolvelib\resolvers.py", line 348, in resolve self._add_to_criteria(self.state.criteria, r, parent=None) File "D:\Anaconda\envs\visgpt\lib\site-packages\pip_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria if not criterion.candidates: File "D:\Anaconda\envs\visgpt\lib\site-packages\pip_vendor\resolvelib\structs.py", line 151, in **bool** return bool(self._sequence) File "D:\Anaconda\envs\visgpt\lib\site-packages\pip_internal\resolution\resolvelib\found_candidates.py", line 155, in **bool** return any(self) File "D:\Anaconda\envs\visgpt\lib\site-packages\pip_internal\resolution\resolvelib\found_candidates.py", line 143, in return (c for c in iterator if id(c) not in self._incompatible_ids) File "D:\Anaconda\envs\visgpt\lib\site-packages\pip_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built candidate = func() File "D:\Anaconda\envs\visgpt\lib\site-packages\pip_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link self._link_candidate_cache[link] = LinkCandidate( File "D:\Anaconda\envs\visgpt\lib\site-packages\pip_internal\resolution\resolvelib\candidates.py", line 297, in **init** super().**init**( File "D:\Anaconda\envs\visgpt\lib\site-packages\pip_internal\resolution\resolvelib\candidates.py", line 162, in **init** self.dist = self._prepare() File "D:\Anaconda\envs\visgpt\lib\site-packages\pip_internal\resolution\resolvelib\candidates.py", line 231, in _prepare dist = self._prepare_distribution() File "D:\Anaconda\envs\visgpt\lib\site-packages\pip_internal\resolution\resolvelib\candidates.py", line 308, in _prepare_distribution return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True) File "D:\Anaconda\envs\visgpt\lib\site-packages\pip_internal\operations\prepare.py", line 491, in prepare_linked_requirement return self._prepare_linked_requirement(req, parallel_builds) File "D:\Anaconda\envs\visgpt\lib\site-packages\pip_internal\operations\prepare.py", line 536, in _prepare_linked_requirement local_file = unpack_url( File "D:\Anaconda\envs\visgpt\lib\site-packages\pip_internal\operations\prepare.py", line 166, in unpack_url file = get_http_url( File "D:\Anaconda\envs\visgpt\lib\site-packages\pip_internal\operations\prepare.py", line 107, in get_http_url from_path, content_type = download(link, temp_dir.path) File "D:\Anaconda\envs\visgpt\lib\site-packages\pip_internal\network\download.py", line 147, in **call** for chunk in chunks: File "D:\Anaconda\envs\visgpt\lib\site-packages\pip_internal\cli\progress_bars.py", line 53, in _rich_progress_bar for chunk in iterable: File "D:\Anaconda\envs\visgpt\lib\site-packages\pip_internal\network\utils.py", line 63, in response_chunks for chunk in response.raw.stream( File "D:\Anaconda\envs\visgpt\lib\site-packages\pip_vendor\urllib3\response.py", line 622, in stream data = self.read(amt=amt, decode_content=decode_content) File "D:\Anaconda\envs\visgpt\lib\site-packages\pip_vendor\urllib3\response.py", line 587, in read raise IncompleteRead(self._fp_bytes_read, self.length_remaining) File "D:\Anaconda\envs\visgpt\lib\contextlib.py", line 131, in **exit** self.gen.throw(type, value, traceback) File "D:\Anaconda\envs\visgpt\lib\site-packages\pip_vendor\urllib3\response.py", line 443, in _error_catcher raise ReadTimeoutError(self._pool, None, "Read timed out.") pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

挂代理了吗，关了试试清华的镜像 pip install -r requirement.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by IssacaLaw** [comment]
> 127.0.0.1

感谢，已进入UI，原以为0.0.00也是本地地址，所以之前一直没试localhost

**Comment by IssacaLaw** [comment]
> 把0.0.0.0改成localhost或者127.0.0.1 http://localhost:7860/

感谢，已进入UI，原以为0.0.00也是本地地址，所以之前一直没试localhost

**Comment by IssacaLaw** [comment]
> 把0.0.0.0改成localhost或者127.0.0.1 http://localhost:7860/

但是进入UI后输出一些命令给visgpt，我挂代理的话，显示，
![image](https://user-images.githubusercontent.com/71266344/224491685-826494f9-38cc-4ce0-a773-8f9f1218e84d.png)
不挂代理的话，显示
![image](https://user-images.githubusercontent.com/71266344/224491692-4666f771-1bdd-4569-95a0-f696c3cba556.png)

**Comment by F4irytale** [comment]
> > 把0.0.0.0改成localhost或者127.0.0.1 http://localhost:7860/
> 
> 但是进入UI后输出一些命令给visgpt，我挂代理的话，显示， ![image](https://user-images.githubusercontent.com/71266344/224491685-826494f9-38cc-4ce0-a773-8f9f1218e84d.png) 不挂代理的话，显示 ![image](https://user-images.githubusercontent.com/71266344/224491692-4666f771-1bdd-4569-95a0-f696c3cba556.png)

我已经放弃本地部署了😥，用别的老哥的colab部署玩玩了

**Comment by 77LJH** [comment]
> @F4irytale 清华源有用欸，但是卡在了最后五个。另外，我打开pycharm的可用软件包是空白，什么都搜索不到，对于requirement里安装好的包好像也看不到。我不知道是为什么，跟第一步部署的python3.8有关吗？
![image](https://user-images.githubusercontent.com/104681814/224492284-8f42ffbd-3248-448d-a54b-836a3e7cad68.png)

**Comment by F4irytale** [comment]
> > @F4irytale 清华源有用欸，但是卡在了最后五个。另外，我打开pycharm的可用软件包是空白，什么都搜索不到，对于requirement里安装好的包好像也看不到。我不知道是为什么，跟第一步部署的python3.8有关吗？
> > ![image](https://user-images.githubusercontent.com/104681814/224492284-8f42ffbd-3248-448d-a54b-836a3e7cad68.png)

我是下的https://www.anaconda.com/这个软件，在命令窗口下执行的前三条语句，双击运行download.sh，再执行set OPENAI_API_KEY={}，和后两条语句，用pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113解决cuda兼容问题，在启动文件调整cuda:1~8选择要使用的gpu，最后死在显存不足和网络不通上😂

**Comment by RickyWang111** [comment]
我输入显示错误。

```
(venv) PS G:\Project_Python\visual-chatgpt-main> bash download.sh
download.sh: line 1: git: command not found
ln: failed to create symbolic link './ldm': File exists
ln: failed to create symbolic link './cldm': File exists
ln: failed to create symbolic link './annotator': File exists        
download.sh: line 5: cd: ControlNet/models: No such file or directory
download.sh: line 6: wget: command not found
download.sh: line 7: wget: command not found
download.sh: line 8: wget: command not found
download.sh: line 9: wget: command not found
download.sh: line 10: wget: command not found
download.sh: line 11: wget: command not found
download.sh: line 12: wget: command not found
download.sh: line 13: wget: command not found

```

**Comment by RickyWang111** [comment]
> 老哥问一下bash download.sh这一步你那边显示的什么？

我输入bash download.sh显示错误。
```

(venv) PS G:\Project_Python\visual-chatgpt-main> bash download.sh
download.sh: line 1: git: command not found
ln: failed to create symbolic link './ldm': File exists
ln: failed to create symbolic link './cldm': File exists
ln: failed to create symbolic link './annotator': File exists        
download.sh: line 5: cd: ControlNet/models: No such file or directory
download.sh: line 6: wget: command not found
download.sh: line 7: wget: command not found
download.sh: line 8: wget: command not found
download.sh: line 9: wget: command not found
download.sh: line 10: wget: command not found
download.sh: line 11: wget: command not found
download.sh: line 12: wget: command not found
download.sh: line 13: wget: command not found
```

**Comment by F4irytale** [comment]
> 我输入bash download.sh显示错误。
> 
> ```
> (venv) PS G:\Project_Python\visual-chatgpt-main> bash download.sh
> download.sh: line 1: git: command not found
> ln: failed to create symbolic link './ldm': File exists
> ln: failed to create symbolic link './cldm': File exists
> ln: failed to create symbolic link './annotator': File exists        
> download.sh: line 5: cd: ControlNet/models: No such file or directory
> download.sh: line 6: wget: command not found
> download.sh: line 7: wget: command not found
> download.sh: line 8: wget: command not found
> download.sh: line 9: wget: command not found
> download.sh: line 10: wget: command not found
> download.sh: line 11: wget: command not found
> download.sh: line 12: wget: command not found
> download.sh: line 13: wget: command not found
> ```

安装git再运行 https://git-scm.com/

**Comment by K-tang-mkv** [comment]
> > 老哥问一下bash download.sh这一步你那边显示的什么？
> 
> 我输入bash download.sh显示错误。
> 
> ```
> 
> (venv) PS G:\Project_Python\visual-chatgpt-main> bash download.sh
> download.sh: line 1: git: command not found
> ln: failed to create symbolic link './ldm': File exists
> ln: failed to create symbolic link './cldm': File exists
> ln: failed to create symbolic link './annotator': File exists        
> download.sh: line 5: cd: ControlNet/models: No such file or directory
> download.sh: line 6: wget: command not found
> download.sh: line 7: wget: command not found
> download.sh: line 8: wget: command not found
> download.sh: line 9: wget: command not found
> download.sh: line 10: wget: command not found
> download.sh: line 11: wget: command not found
> download.sh: line 12: wget: command not found
> download.sh: line 13: wget: command not found
> ```

先根据你的系统安装`git`, 再安装`wget`，

**Comment by K-tang-mkv** [comment]
@IssacaLaw 
好对的，本地在localhost访问即可，这个我也疏忽了。如果你`share=True`的话，它不仅会提供一个私有的本地访问地址，还会有一个public的网址可以访问的。

**Comment by K-tang-mkv** [comment]
> > > @F4irytale 清华源有用欸，但是卡在了最后五个。另外，我打开pycharm的可用软件包是空白，什么都搜索不到，对于requirement里安装好的包好像也看不到。我不知道是为什么，跟第一步部署的python3.8有关吗？
> > > ![image](https://user-images.githubusercontent.com/104681814/224492284-8f42ffbd-3248-448d-a54b-836a3e7cad68.png)
> 
> 我是下的[https://www.anaconda.com/这个软件，在命令窗口下执行的前三条语句，双击运行download.sh，再执行set](https://www.anaconda.com/%E8%BF%99%E4%B8%AA%E8%BD%AF%E4%BB%B6%EF%BC%8C%E5%9C%A8%E5%91%BD%E4%BB%A4%E7%AA%97%E5%8F%A3%E4%B8%8B%E6%89%A7%E8%A1%8C%E7%9A%84%E5%89%8D%E4%B8%89%E6%9D%A1%E8%AF%AD%E5%8F%A5%EF%BC%8C%E5%8F%8C%E5%87%BB%E8%BF%90%E8%A1%8Cdownload.sh%EF%BC%8C%E5%86%8D%E6%89%A7%E8%A1%8Cset) OPENAI_API_KEY={}，和后两条语句，用pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1+cu113 --extra-index-url [https://download.pytorch.org/whl/cu113解决cuda兼容问题，在启动文件调整cuda:1~8选择要使用的gpu，最后死在显存不足和网络不通上😂](https://download.pytorch.org/whl/cu113%E8%A7%A3%E5%86%B3cuda%E5%85%BC%E5%AE%B9%E9%97%AE%E9%A2%98%EF%BC%8C%E5%9C%A8%E5%90%AF%E5%8A%A8%E6%96%87%E4%BB%B6%E8%B0%83%E6%95%B4cuda:1~8%E9%80%89%E6%8B%A9%E8%A6%81%E4%BD%BF%E7%94%A8%E7%9A%84gpu%EF%BC%8C%E6%9C%80%E5%90%8E%E6%AD%BB%E5%9C%A8%E6%98%BE%E5%AD%98%E4%B8%8D%E8%B6%B3%E5%92%8C%E7%BD%91%E7%BB%9C%E4%B8%8D%E9%80%9A%E4%B8%8A%F0%9F%98%82)

如果显存不足的话，你可以在`self.tools`里选择需要的模型，根据你显存大小来选择合适的模型，checkout this readme [![Open 2k image generation in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1bl-JAgrUru9GlGsb9hrcZCqj3uI6ev_O?usp=sharing)。或者你可以参考我的colab版本[https://github.com/K-tang-mkv/visual-chatgpt-googlecolab](https://github.com/K-tang-mkv/visual-chatgpt-googlecolab)

**Comment by wggglggg** [comment]
requirement.txt的第3行与第5行指定的版本都装不了，大家怎么处理的，我用的py3.7，有人用3.7版吗？

**Comment by wrk226** [comment]
> requirement.txt的第3行与第5行指定的版本都装不了，大家怎么处理的，我用的py3.7，有人用3.7版吗？

换成3.8不就完事了，干嘛坚持3.7。另外你有其他问题最好新开一个issue。

**Comment by huanghan2001** [comment]
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/52448257/224533083-f0156cfa-1757-4687-bdf6-206e260ad1ff.png">
为什么我进去是白屏呀

**Comment by Ableable96** [comment]
> @IssacaLaw 或者你可以参考一下我的colab notebook https://github.com/K-tang-mkv/visual-chatgpt-googlecolab, 我在visual-chatgpt.py里修改最后一行的启动方式，使其能公共访问。 ![Screen Shot 2023-03-11 at 7 57 59 PM](https://user-images.githubusercontent.com/59059785/224483002-c6e24f35-6d4a-4176-a387-8fe75b87627e.png)

大佬，我也是在colab上跑，最后界面打开了，但打了个招呼后就报错了，如下：
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
我试着把CUDA版本降到和torch相匹配的11.6，但还是报错，我尝试把你的colab文件也跑了一遍，最后还是这个报错，你知道该怎么解决吗？感激不尽！

**Comment by Ableable96** [comment]
> @IssacaLaw 你是在本地运行的吗，如果是服务器的话是不能直接这样访问的，要么设置`share=True`, 或者转发到本地端口进行访问

大佬，我也是在colab上跑，最后界面打开了，但打了个招呼后就报错了，如下：
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
我试着把CUDA版本降到和torch相匹配的11.6，但还是报错，我尝试把你的colab文件也跑了一遍，最后还是这个报错，你知道该怎么解决吗？感激不尽！

**Comment by Ableable96** [comment]
> @IssacaLaw 你是在本地运行的吗，如果是服务器的话是不能直接这样访问的，要么设置`share=True`, 或者转发到本地端口进行访问

大佬，我也是在colab上跑，最后界面打开了，但打了个招呼后就报错了，如下： RuntimeError: CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. 我试着把CUDA版本降到和torch相匹配的11.6，但还是报错，我尝试把你的colab文件也跑了一遍，最后还是这个报错，你知道该怎么解决吗？感激不尽！

**Comment by Guojingxing** [comment]
![image](https://user-images.githubusercontent.com/33157458/224644128-6aff6d2f-e211-40a0-8265-a811f765fdba.png)
![image](https://user-images.githubusercontent.com/33157458/224644177-9f621d89-3492-4dde-b632-d1478578798c.png)
安装了git，还是出现错误

**Comment by K-tang-mkv** [comment]
> > @IssacaLaw 你是在本地运行的吗，如果是服务器的话是不能直接这样访问的，要么设置`share=True`, 或者转发到本地端口进行访问
> 
> 大佬，我也是在colab上跑，最后界面打开了，但打了个招呼后就报错了，如下： RuntimeError: CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. 我试着把CUDA版本降到和torch相匹配的11.6，但还是报错，我尝试把你的colab文件也跑了一遍，最后还是这个报错，你知道该怎么解决吗？感激不尽！

你好，这个error出现是因为pytorch和cuda的版本并不兼容，而我的colab项目中`torch==1.12.1` `cuda=12.0`, 最后是可以成功运行的，确保你开了新notebook运行我的colab版本，应该是没问题的。

**Comment by caopeng000** [comment]
老哥能出个教程不。关注你

**Comment by limumua** [comment]
> > requirement.txt的第3行与第5行指定的版本都装不了，大家怎么处理的，我用的py3.7，有人用3.7版吗？
> 
> 换成3.8不就完事了，干嘛坚持3.7。另外你有其他问题最好新开一个issue。

老哥 怎么用Azure的openai啊，我把key换成Azure的也不行，在src文件里的配置文件和代码中都给了试过，还是不行，打印输出根本就没走到那，有办法吗

**Comment by yanhualengluo** [comment]
为什么后面即使是http://localhost:7860，会“localhost 已拒绝连接”哇，也是开了FTP服务了

**Comment by WEXIJUE** [comment]
> @IssacaLaw或者你可以参考一下我的colab笔记本https://github.com/K-tang-mkv/visual-chatgpt-googlecolab，我在visual-chatgpt.py里修改最后一行的启动方式，使其能够公共访问。 ![屏幕截图 2023 年 3 月 11 日下午 7 点 57 分 59 分](https://user-images.githubusercontent.com/59059785/224483002-c6e24f35-6d4a-4176-a387-8fe75b87627e.png)

哥，我是用学校的服务器来部署的，也是打不开本地连接，我该怎么改，求告知，非常感谢

**Comment by NGCcolor** [comment]
> 把0.0.0.0改成localhost或者127.0.0.1![屏幕截图 2024-09-25 132147](https://github.com/user-attachments/assets/f7f85687-5e6d-4d31-a4d6-75911de36eec)

![屏幕截图 2024-09-25 131924](https://github.com/user-attachments/assets/d74dd929-32c6-4a32-8ea1-dc69674db849)
还是无法进入页面，老哥有办法嘛

**Comment by MikingG** [comment]
If you’re running LlamaFactory on a server, you obviously can’t just type in the local URL http://0.0.0.0:7860/ on your own computer. Instead, you’ll need to use the shared link.

If you see instructions saying files are missing, make sure to follow those instructions and download the necessary files. If no such instructions appear, you can skip this step.

Here’s the key step that had me stuck for a while:
First, add executable permissions by running:
`chmod +x /root/miniconda3/lib/python3.10/site-packages/gradio/frpc_linux_amd64_v0.2`
Then, start the application with:
`GRADIO_SHARE=1 llamafactory-cli webui`

At this point, you should see the shared link. 😊
If you’re using AutoDL and want to open the local URL http://0.0.0.0:7860/, you can refer to this guide: https://blog.csdn.net/weixin_72977159/article/details/140614273

---

如果你是用服务器跑的llamafactory，那当然不能在自己的电脑里面输入 local URL: http://0.0.0.0:7860/，但可以用shared link。
如果有指示说文件缺失，那就先按照指示下载好文件。如果没有这步可以跳过。
让我一直卡住的关键一步：先添加可执行权限 chmod +x /root/miniconda3/lib/python3.10/site-packages/gradio/frpc_linux_amd64_v0.2
再运行 GRADIO_SHARE=1 llamafactory-cli webui

然后就应该能看到shared link了

如果你在AutoDL中想打开local URL: http://0.0.0.0:7860/ ，可以参考 https://blog.csdn.net/weixin_72977159/article/details/140614273
