### ISSUE TITLE
 error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by Gigibang-Yin** [microsoft/visual-chatgpt#87]
error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator.DESKTOP-4G9BJ49\AppData\Local\Temp\pip-install-x6dcgvkx\basicsr_4bee4e8adfc94fb9be8dda8f0b7a547b\setup.py", line 147, in <module>
          setup(
        File "E:\Coding\VsCode\visual-chatgpt\venv\lib\site-packages\setuptools\__init__.py", line 152, in setup
          _install_setup_requires(attrs)
        File "E:\Coding\VsCode\visual-chatgpt\venv\lib\site-packages\setuptools\__init__.py", line 147, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "E:\Coding\VsCode\visual-chatgpt\venv\lib\site-packages\setuptools\dist.py", line 785, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "E:\Coding\VsCode\visual-chatgpt\venv\lib\site-packages\pkg_resources\__init__.py", line 766, in resolve
          dist = best[req.key] = env.best_match(
        File "E:\Coding\VsCode\visual-chatgpt\venv\lib\site-packages\pkg_resources\__init__.py", line 1051, in best_match
          return self.obtain(req, installer)
        File "E:\Coding\VsCode\visual-chatgpt\venv\lib\site-packages\pkg_resources\__init__.py", line 1063, in obtain
          return installer(requirement)
        File "E:\Coding\VsCode\visual-chatgpt\venv\lib\site-packages\setuptools\dist.py", line 844, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "E:\Coding\VsCode\visual-chatgpt\venv\lib\site-packages\setuptools\installer.py", line 80, in fetch_build_egg
          wheel.install_as_egg(dist_location)
        File "E:\Coding\VsCode\visual-chatgpt\venv\lib\site-packages\setuptools\wheel.py", line 95, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "E:\Coding\VsCode\visual-chatgpt\venv\lib\site-packages\setuptools\wheel.py", line 103, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "E:\Coding\VsCode\visual-chatgpt\venv\lib\site-packages\setuptools\wheel.py", line 125, in _convert_metadata
          zf.extractall(destination_eggdir)
        File "C:\Users\Administrator.DESKTOP-4G9BJ49\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1645, in extractall
          self._extract_member(zipinfo, path, pwd)
        File "C:\Users\Administrator.DESKTOP-4G9BJ49\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1699, in _extract_member
          open(targetpath, "wb") as target:
      FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator.DESKTOP-4G9BJ49\\AppData\\Local\\Temp\\pip-install-x6dcgvkx\\basicsr_4bee4e8adfc94fb9be8dda8f0b7a547b\\.eggs\\torch-1.13.1-py3.10-win-amd64.egg\
\torch\\include\\ATen\\ops\\upsample_trilinear3d_backward_compositeexplicitautogradnonfunctional_dispatch.h'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by wrk226** [comment]
You shouldn't use torch-1.13.1, please use the same version as in the requirements.txt.

**Comment by felipe-parodi** [comment]
Encountered the same issue in windows-- solved with `conda install torch==1.12.1` before pip installing the requirements
