### ISSUE TITLE
No module named 'chardet'

### ISSUE THREAD

**Issue by javadroid** [microsoft/visual-chatgpt#88]
Traceback (most recent call last):
  File "C:\Users\user\.conda\envs\visgpt\lib\site-packages\requests\compat.py", line 11, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "visual_chatgpt.py", line 5, in <module>
    import gradio as gr
  File "C:\Users\user\.conda\envs\visgpt\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\Users\user\.conda\envs\visgpt\lib\site-packages\gradio\components.py", line 32, in <module>
    from gradio import media_data, processing_utils, utils
  File "C:\Users\user\.conda\envs\visgpt\lib\site-packages\gradio\processing_utils.py", line 20, in <module>
    import requests
  File "C:\Users\user\.conda\envs\visgpt\lib\site-packages\requests\__init__.py", line 45, in <module>
    from .exceptions import RequestsDependencyWarning
  File "C:\Users\user\.conda\envs\visgpt\lib\site-packages\requests\exceptions.py", line 9, in <module>
    from .compat import JSONDecodeError as CompatJSONDecodeError
  File "C:\Users\user\.conda\envs\visgpt\lib\site-packages\requests\compat.py", line 13, in <module>
    import charset_normalizer as chardet
  File "C:\Users\user\.conda\envs\visgpt\lib\site-packages\charset_normalizer\__init__.py", line 23, in <module>
    from charset_normalizer.api import from_fp, from_path, from_bytes, normalize
  File "C:\Users\user\.conda\envs\visgpt\lib\site-packages\charset_normalizer\api.py", line 10, in <module>
    from charset_normalizer.md import mess_ratio
  File "charset_normalizer\md.py", line 5, in <module>
ImportError: cannot import name 'COMMON_SAFE_ASCII_CHARACTERS' from 'charset_normalizer.constant' (C:\Users\user\.conda\envs\visgpt\lib\site-packages\charset_normalizer\constant.py)

**Comment by wrk226** [comment]
Please make sure your torch version is 1.12.1

**Comment by elicassion** [comment]
```
pip install chardet
pip install cchardet
```
if you switch to later pytorch versions. Worked for me on pytorch 1.13

**Comment by mlxu995** [comment]
> ```
> pip install chardet
> pip install cchardet
> ```
> 
> if you switch to later pytorch versions. Worked for me on pytorch 1.13

Thanks, it also works for me on pytorch 2.3.0
